#!/bin/sh
# Script to run AliEn on LCG
# Automatically generated by AliEn running on ui01-alice.cr.cnaf.infn.it

export HOME=`pwd`
echo --- hostname, uname, whoami, pwd --------------
hostname
uname -a
whoami
pwd

echo --- ls -la ------------------------------------
ls -lart
echo --- df ----------------------------------------
df -h
echo --- free --------------------------------------
free

cat /proc/cpuinfo

#!/bin/bash

export GSHELL_ROOT=/cvmfs/alice.cern.ch/x86_64-2.6-gnu-4.1.2/Packages/AliEn/v2-19-276
export PATH=$PATH:$GSHELL_ROOT/api/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GSHELL_ROOT/api/lib
export ALIEN_ROOT=$GSHELL_ROOT
source /cvmfs/alice.cern.ch/x86_64-2.6-gnu-4.1.2/Packages/ROOT/v5-34-30-alice-9/bin/thisroot.sh

echo --- env ---------------------------------------
echo $PATH
echo $LD_LIBRARY_PATH
voms-proxy-info -all

unzip mycode.zip

# simulation
chmod a+x compilasim.sh
./compilasim.sh
./sim.exe

# analysis
root -b -q -l myanalysis.C
